### ISSUE TITLE
How to work with the row ID's?

### ISSUE THREAD

**Issue by teamplayer3** [LHolten/rust-query#21]
For example, I have a player in my schema with a name col. I want to get the ID (primary key - you create for every table) when inserting this player to retrieve it afterwords by this ID. Can I do it like this, or is the idea that you don't use the ID and have to insert a player_id column yourself and use it as unique?

When inserting a column `id` as unique, it conflicts with the primary key `id`.

**Comment by LHolten** [comment]
Does the `TableRow` type not do what you want?
`TableRow` is a typed wrapper for the row id that only lives for the length of the transaction.

The `TableRow` is automatically returned when you insert a row into the database.
```rust
let player: TableRow<Player> = txn.try_insert(Player {
    name: "my player",
}).unwrap();
```

Do you want to have an owned version of the row id to reuse between `Transactions`?
If so then it would help me to know more about your use case.

**Comment by LHolten** [comment]
Another example of `TableRow` use.
```rust
// new_players: Vec<TableRow<Player>>
let new_players = txn.query(|rows|{
     let player = Player::join(rows);
     rows.filter(player.score().eq(0));
     rows.into_vec(player)
});

for player in new_players {
    // this does an additional query for every player!
    println!("{}", txn.query_one(player.name()));
}
```

**Comment by teamplayer3** [comment]
I want to pass on these retrieved objects to the frontend. The ID should be usable across `Transactions` to identify these objects. So yes, an owned row.

**Comment by LHolten** [comment]
If it is for the frontend then I think my comment on hacker news is relevant https://news.ycombinator.com/item?id=42289251

So my advice would be:
- Do you already have any unique constraints? If so then consider using those to identify the row across `Transaction`s and in the frontend.
- Otherwise, add a new column with a name like `pub_id` (meaning "public identifer") and type `i64` and add a (named) unique constraint and initialize it with a random integer.
```rust
#[schema]
enum Schema {
    Player {
        #[unique_pub_id] // named unique constraint allows you to have more than 1 unique constraint
        pub_id: i64,
        // other stuff ..
    }
}
```

In my personal [project](https://github.com/LHolten/advent-of-wasm/) (which is a server and frontend) I have not yet had to create an artificial key.
The things I communicate with the frontend all have a nice unique property that I can use:
- Users all have a github id which is unique.
- Files all have a unique hash.
- Challenges have a unique name.
- Benchmark results are identified by the combination of a challenge and a file.

At $work we use postgresql and just have `pub_id` columns on all tables. Those `pub_id`s are UUIDv7 if i remember correctly and it works quite nicely.

**Comment by teamplayer3** [comment]
Thanks for this advice. Helped a lot. Will follow it for further development. Think it's nice that this crate will avoid making the row ID public, following best practices.
